name: Deployment with linting and unit testing
on:
  push:
    branches: [main, upload-dist, control-job-workflow]
jobs:
  Runs-Test-On-Ubuntu:
    name: Runs npm test
    runs-on: Ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Set cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Run testing
        run: npm run test
  Upload-Artifact-File:
    name: Archive production artifacts
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
        if: steps.cache.outputs.cache-hit != 'true'
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist
  Deploy:
    name: Deploy build file
    runs-on: Ubuntu-latest
    needs: Upload-Artifact-File
    steps: 
      - uses: actions/download-artifact@v3
        with:
          name: dist-files
      - run: ls
      - run: echo "Deploying guys"