name: Deployment with linting and unit testing
on:
  push:
    branches: [main, upload-dist]
jobs:
  Runs-Build-On-Ubuntu:
    name: Runs npm build
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      name: Npm run bild
        run: npm install
   